language: python
python:
  - 3.6

cache: pip

addons:
  apt:
    packages:
      - libssl-dev
      - python3-dev

before_install:
  - cat test-requirements.txt >> requirements.txt

script:
  - coala --non-interactive -V
  - python -m pytest -s

notifications:
  email: false
